# Generated by Django 5.2.11 on 2026-02-22 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0002_folder_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='is_listed_in_feed',
            field=models.BooleanField(default=True),
        ),
    ]
