# Generated by Django 5.2.11 on 2026-02-23 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0003_alter_folder_is_listed_in_feed'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='folder_code',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True),
        ),
    ]
